# Site Info
title:              "Frinky"
description:        "Your skin is the ocean."
google_verify:       # Put your Google Verification here
google_analytics:   UA-90247317-1

# Site Settings
baseurl:            "frinky.github.io" # Base URL must end WITHOUT a slash, default: ""

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "CNAME", ".DS_Store" ]
gems:
  - jekyll-sitemap


defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
